### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by asadrao11** [Soundnode/soundnode-app#1055]
Hey i am using node version 8, i am getting the following errors while using npm i.
npm i

> node-sass@4.9.0 install /root/soundnode-app/node_modules/node-sass
> node scripts/install.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/soundnode-app/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-04T13_45_09_160Z-debug.log

**Comment by jakejarrett** [comment]
This is an issue with `node-sass`, try running `npm i node-sass` and it should give you a more specific error.
