### ISSUE TITLE
Stuck on loading the authentication 

### ISSUE THREAD

**Issue by pendar747** [Soundnode/soundnode-app#758]
Launching the app produces the following error:
```
TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^
```
Which leaves the *Authentication your soundcloud account* running forever.

### My system and installation
- Ubuntu 16.04
- npm v2.15.1
- node v4.4.3

Could be of help: I had previously logged in using a .deb package through facebook login.

**Comment by crossdsection** [comment]
Found the same error on my system.

**My system and installation**

- Fedora Release 23
- npm v1.3.6
- node v0.10.42

**Comment by crossdsection** [comment]
I may have found a reason of this happening,

` popUp = gui.Window.open('http://sc-redirect.herokuapp.com/', {
        show: false
    });

    authenticationId = window.setInterval(function () {
        console.log(popUp);
        that.verification(popUp);
    }, 1500);`

In this code, `http://sc-redirect.herokuapp.com/` this URL needs to get hit and a popup of logging in comes automatically. I tried opening the URL on browser and the Pop Up got blocked by Chrome. When I allowed the pop up, it worked on the browser. 

I searched the extension-Id- 'homeedcegkeacgfpkinccjdhmgehmgif', and found only two pages those were connected with Soundnode bugs only.

I'm a noob, just an assumption that this chrome extension is probably an internal extension of Chrome, and it is blocking the pop up. Even after allowing the pop up in the browser, the terminal was not able to access it properly. Can someone guide me in allowing the URL?

**Comment by jakejarrett** [comment]
You need to run it via nwjs, there's instructions on the wiki on how to build it

**Comment by crossdsection** [comment]
I did followed [the](https://github.com/Soundnode/soundnode-app/wiki/Development) wiki, and ran it with nwjs only.. But still I was getting this error. So is the problem is with my nwjs installation?

**Comment by pendar747** [comment]
This is most likely an issue with nw js `window.open()` method. For some reason it returns `undefined` instead of a window instance and also it doesnt redirict the page once `'http://sc-redirect.herokuapp.com/'` is loaded. I tried this with nw js 0.15.0

**Comment by swapnas** [comment]
It doesn't work because the behavior of the function is changed. Its Window.open(url, [options], [callback]).
where the window is passed as the argument in the callback.

**Comment by weblancaster** [comment]
You need to have the exactly version we are using.. so use the nwjs from cache folder https://github.com/Soundnode/soundnode-app/tree/master/cache/0.12.3 instead downloading an updated version

**Comment by wb9688** [comment]
@weblancaster: Shouldn't we upgrade to the latest nw.js or even the latest
Electron?

**Comment by Pitros** [comment]
@wb9688 on latest nw.js soundcloud login window does not show - probably because nw.js blocks popups (or that is just a bug, and that's why we're still running 0.12). Electron would require rewriting whole window management.

**Comment by wb9688** [comment]
@pjotr: I know, but I'm willing to write the code for moving to Electron
when I get home… (I'm at vacation rn)

**Comment by weblancaster** [comment]
Haha so do it @wb9688

**Comment by apoliveira** [comment]
Is there any update on this? pop-up still not showing/the app is still stuck on authenticating your account
