### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by JonasGroeger** [Soundnode/soundnode-app#831]
I have no idea what causes this.

```

$ dist/Soundnode/linux64/Soundnode 
[3062:0724/154611:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Gtk-Message: Failed to load module "overlay-scrollbar"
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[3062:0724/154611:ERROR:nw_shell.cc(336)] Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/tmp/.org.chromium.Chromium.RQ97IJ/node_modules/universal-analytics/lib/index.js:4:15)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
[3062:0724/154611:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'request'", source: module.js (329)
[3062:0724/154611:INFO:CONSOLE(13)] ""User is saved"", source: file:///tmp/.org.chromium.Chromium.RQ97IJ/public/js/system/userConfig.js (13)
[3062:0724/154611:INFO:CONSOLE(16)] ""Download the React DevTools for a better development experience: https://fb.me/react-devtools"", source: file:///tmp/.org.chromium.Chromium.RQ97IJ/dist/bundle.js (16)
[3062:0724/154613:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'visitor' of undefined
    at file:///tmp/.org.chromium.Chromium.RQ97IJ/public/js/app.js:102:20
    at Object.e [as invoke] (file:///tmp/.org.chromium.Chromium.RQ97IJ/public/js/vendor/angular.min.1.3.8.js:37:96)
    at file:///tmp/.org.chromium.Chromium.RQ97IJ/public/js/vendor/angular.min.1.3.8.js:38:454
    at s (file:///tmp/.org.chromium.Chromium.RQ97IJ/public/js/vendor/angular.min.1.3.8.js:7:302)
    at Ob (file:///tmp/.org.chromium.Chromium.RQ97IJ/public/js/vendor/angular.min.1.3.8.js:38:433)
    at d (file:///tmp/.org.chromium.Chromium.RQ97IJ/public/js/vendor/angular.min.1.3.8.js:17:350)
    at Object.sc [as bootstrap] (file:///tmp/.org.chromium.Chromium.RQ97IJ/public/js/vendor/angular.min.1.3.8.js:18:153)
    at file:///tmp/.org.chromium.Chromium.RQ97IJ/public/js/system/authentication.js:60:17
[3062:0724/154613:INFO:CONSOLE(102)] "Uncaught TypeError: Cannot read property 'visitor' of undefined", source: file:///tmp/.org.chromium.Chromium.RQ97IJ/public/js/app.js (102)

```

**Comment by Pitros** [comment]
More details? You're running built app or launching from git?

**Comment by JonasGroeger** [comment]
I'm using the git version

**Comment by Pitros** [comment]
Did you use npm install etc.?

**Comment by JonasGroeger** [comment]
@Pitros Yes, ofc. I used the Makefile

**Comment by Pitros** [comment]
@JonasGroeger try installing it manually - `npm install request`, that should help.

**Comment by JonasGroeger** [comment]
I did. You can check my branch at https://github.com/JonasGroeger/soundnode-app/tree/feature/fix-webpack-cmd

**Comment by weblancaster** [comment]
what's your node and npm version @JonasGroeger ?

**Comment by weblancaster** [comment]
although that log looks like it's a NW.js issue.

**Comment by JonasGroeger** [comment]
$ npm -v
    3.10.3

    $node -v
    v6.3.0

**Comment by weblancaster** [comment]
I don't think will help with this particular issue but the current version to run locally you need to have npm < 3 and which requires node < 5
