### ISSUE TITLE
Suggestion for animation.

### ISSUE THREAD

**Issue by jeexzee** [Soundnode/soundnode-app#852]
When you hover over tracks the animation looks wierd. Instead of the black beeing flown in it would be better if it faded in.

Also animations on play/pause on the track would be awesome!

**Comment by ZeeCoder** [comment]
I definitely agree, I was just thinking about doing something about it.
Not sure how hard it is to work on an electron app, but from what I heard it should be simple enough.

**Comment by wb9688** [comment]
@ZeeCoder: This is a nwjs app and not an Electron app. Btw this could be
fixed by adding a CSS animation, but I'm not 100% sure that this old
version of nwjs (0.12.3) has support for CSS animations…

**Comment by Ajeey** [comment]
What is the suggested animation? I could send in a PR right away.

**Comment by ZeeCoder** [comment]
@wb9688 you should contact the electron guys then, it's listed here: http://electron.atom.io/apps/

**Comment by wb9688** [comment]
@ZeeCoder: I won't contact the Electron guys as I'm going to port it to
Electron next week. Btw I've no idea why it's on that list…

**Comment by ZeeCoder** [comment]
@wb9688 awesome, I'll look into it once you did that then.
Could you relate the MR and this issue so that I get a notification?
Cheers!

**Comment by wb9688** [comment]
@ZeeCoder: You could start now; the change to Electron will only affect the
build scripts and the SoundCloud login part…

**Comment by ZeeCoder** [comment]
Ah cool, thought they were less compatible for some reason 👍

**Comment by ZeeCoder** [comment]
Tried to fire up the app, got the following:

<details>
<summary>Output</summary>
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^

TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^

TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^

TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^

TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^

TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^

TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^

TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^

TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^

TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^

TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31
    if (popUp.window.document.body !== null) {
             ^

TypeError: Cannot read property 'window' of undefined
    at Object.authentication.verification (chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:31:14)
    at chrome-extension://homeedcegkeacgfpkinccjdhmgehmgif/app/public/js/system/authentication.js:22:14
</summary>

Any ideas? (I'm on a Mac btw.)

**Comment by Pitros** [comment]
You need to use NW.js versions from cache folder, not the latest ones (0.13 was rewritten and many things changed)

**Comment by wb9688** [comment]
Yeah, look at the wiki…

Op 28 aug. 2016 21:42 schreef "Piotr Cholewa" <notifications@github.com>:

**Comment by ZeeCoder** [comment]
Changed the animation in the above referenced PR.

btw @wb9688 where is this in the wiki? For the life of me I can't find it.
I only found this in the wiki: https://github.com/Soundnode/soundnode-app/wiki/Development
And this in the readme file: https://github.com/nwjs/nw.js/wiki/How-to-run-apps

If your intention with the latter was to point out that the project uses v0.13,
then it's not obvious: I went on to download the latest assuming the 3rd party readme page was simply outdated.
