### ISSUE TITLE
nw_shell.cc(336) Error: Cannot find module 'inherits'

### ISSUE THREAD

**Issue by JonasGroeger** [Soundnode/soundnode-app#876]
I'm getting the error after building the debian package from master with `make deb`.

```
$ npm -v
3.10.8
```

```
$ soundnode
[23972:0917/205808:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Gtk-Message: Failed to load module "overlay-scrollbar"
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[23972:0917/205809:ERROR:nw_shell.cc(336)] Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/tmp/.org.chromium.Chromium.qYHLFu/node_modules/universal-analytics/node_modules/request/node_modules/bl/node_modules/readable-stream/lib/_stream_duplex.js:26:17)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
[23972:0917/205809:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'inherits'", source: module.js (329)
```

**Comment by weblancaster** [comment]
you got use npm version  < 3

**Comment by JonasGroeger** [comment]
@weblancaster I dont get what you are trying to say

**Comment by wb9688** [comment]
@weblancaster: Not if you use the parameter I listed at the wiki. I can
build the latest commit (and every commit since I started reacting at the
GitHub issues of this project) fine on my Debian machine…

**Comment by JonasGroeger** [comment]
@wb9688 can you link the page?

**Comment by wb9688** [comment]
@JonasGroeger: `rm -rf node_modules/ && npm i --legacy-bundling` would fix
the problem you're having if I'm right…
