### ISSUE TITLE
How do I use the source?

### ISSUE THREAD

**Issue by Legitgamer264** [Soundnode/soundnode-app#925]
which branch would i pull from to get the latest version, beta wise? I don't mind bugs, I enjoy beta testing. Would I pull/clone the electron-migration branch? I know how to do the rest I just don't know which version to clone.

**Comment by weblancaster** [comment]
@Legitgamer264 after cloning the repository you can run `git fetch --all` then `git checkout electron-migration` now you should be able to see the "new" code for the migration.

start with `npm i` to install the required modules then you can build to your platform.
`npm run package:osx` for mac, `npm run package:win32` for windows which you need to have wine installed https://www.winehq.org/ and `npm run package:linux` for linux (`npm run package:all` build for all platforms).

**Comment by Legitgamer264** [comment]
alrighty. I will be home in an hour and a half. Will give the new update a try

**Comment by weblancaster** [comment]
@Legitgamer264 No worries and no rush. thanks a lot!

**Comment by Legitgamer264** [comment]
@weblancaster you're welcome. If you need anything, just let me know. I would love to help in any way I can

**Comment by Legitgamer264** [comment]
@weblancaster about how long should it take to package the app that I got from the source? For win32

**Comment by Legitgamer264** [comment]
@weblancaster is there a reason why it takes awhile to package the app using `npm run package:win32`

**Comment by weblancaster** [comment]
@Legitgamer264 yes, need to compile the code and package everything.. but should take perhaps a 1 min.

**Comment by Legitgamer264** [comment]
@weblancaster I just deleted the app and re-cloned it. I did it wrong the first time. Now it packaged much faster

**Comment by Legitgamer264** [comment]
I had the previous version, non electron, and I thought just putting electron-migration over that would work. That is why it took so long to package. it was like a 1GB folder

**Comment by wb9688** [comment]
@weblancaster: With npm 3+ it should be `npm i --legacy-bundling`…

**Comment by 719Ben** [comment]
I am trying to do `npm run package:osx`  @weblancaster and I get the following:

```
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/Ben/.nvm/versions/node/v6.9.1/bin/node" "/Users/Ben/.nvm/versions/node/v6.9.1/bin/npm" "run" "package:osx"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! missing script: package:osx
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ben/GitHub/soundnode-app/npm-debug.log
```

and the following in the debug file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/Ben/.nvm/versions/node/v6.9.1/bin/node',
1 verbose cli   '/Users/Ben/.nvm/versions/node/v6.9.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'package:osx' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose stack Error: missing script: package:osx
4 verbose stack     at run (/Users/Ben/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /Users/Ben/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /Users/Ben/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/Users/Ben/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/Users/Ben/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/Users/Ben/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /Users/Ben/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /Users/Ben/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd /Users/Ben/GitHub/soundnode-app
6 error Darwin 16.1.0
7 error argv "/Users/Ben/.nvm/versions/node/v6.9.1/bin/node" "/Users/Ben/.nvm/versions/node/v6.9.1/bin/npm" "run" "package:osx"
8 error node v6.9.1
9 error npm  v3.10.8
10 error missing script: package:osx
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

Any ideas what I am doing wrong?

**Comment by weblancaster** [comment]
@719Ben this is for the new migration work which isn't in master yet.

To be able to run what you tried you need to checkout to branch `https://github.com/Soundnode/soundnode-app/tree/electron-migration`

**Comment by 719Ben** [comment]
@weblancaster I am on the electron-migration branch

**Comment by 719Ben** [comment]
@weblancaster okay I have the app building but can't figure out how to build any of the css/js files. Any ideas? Thanks for all the help!

**Comment by weblancaster** [comment]
to build the css `npm run sass:dev` to build js `npm run webpack:dev` (note that `webpack:dev` will watch for changes in the jsx files).

If you want to build for development purpose I suggest using `npm run watch` this is going to start the css and js tasks and watch for any changes in them.
